# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pers_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('entry', models.CharField(max_length=11)),
                ('branch', models.CharField(max_length=32)),
                ('dob', models.DateField(verbose_name='Date Of Birth')),
                ('Age', models.IntegerField(default=0)),
                ('contact_no', models.IntegerField(max_length=10)),
                ('contact_id', models.CharField(max_length=32)),
            ],
        ),
    ]
