# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pers_info',
            name='contact_no',
            field=models.IntegerField(default=0),
        ),
    ]
